definitions:
  bookEntity.Book:
    properties:
      author:
        type: string
      id:
        type: string
      publisherDay:
        type: string
      title:
        type: string
    type: object
  bookEntity.CreateBookRequest:
    properties:
      author:
        type: string
      title:
        type: string
    type: object
  bookEntity.UpdateBookRequest:
    properties:
      author:
        type: string
      publisherDay:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /book:
    get:
      consumes:
      - application/json
      description: New create book
      parameters:
      - description: field
        in: query
        name: field
        required: true
        type: string
      - description: value
        in: query
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bookEntity.Book'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: GetBook
      tags:
      - book
  /book/:
    get:
      consumes:
      - application/json
      description: New create book
      parameters:
      - description: field
        in: query
        name: field
        required: true
        type: string
      - description: value
        in: query
        name: value
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/bookEntity.Book'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: GetBooks
      tags:
      - book
  /book/create:
    post:
      consumes:
      - application/json
      description: New create book
      parameters:
      - description: Create new user book
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/bookEntity.CreateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bookEntity.Book'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: createBook
      tags:
      - book
  /book/delete:
    delete:
      consumes:
      - application/json
      description: New create book
      parameters:
      - description: field
        in: query
        name: field
        required: true
        type: string
      - description: value
        in: query
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: createBook
      tags:
      - book
  /book/update:
    put:
      consumes:
      - application/json
      description: New create book
      parameters:
      - description: Create new user book
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/bookEntity.UpdateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bookEntity.Book'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: createBook
      tags:
      - book
swagger: "2.0"
